package CRUD_Resort;

import java.sql.Connection;

/**
 *
 * @author Oscar Caceres y Henry Fiallos
 */
public class principal extends javax.swing.JFrame {
    //conexion conn = new conexion();
    //Connection cn=conn.Conectar();
    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
    }
    /**
     * ADVERTENCIA: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_habitaciones = new javax.swing.JButton();
        btn_empleados = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_reserva = new javax.swing.JButton();
        btn_huesped = new javax.swing.JButton();
        btn_facturas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_accesos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 0));
        jPanel1.setName("Control Administrativo Hotelero"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Magneto", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 102));
        jLabel1.setText("CaceresFiallos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 409, -1));

        btn_habitaciones.setBackground(new java.awt.Color(204, 255, 102));
        btn_habitaciones.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btn_habitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HABITACION.png"))); // NOI18N
        btn_habitaciones.setText("Habitaciones");
        btn_habitaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_habitaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_habitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_habitacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_habitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 230, 160));

        btn_empleados.setBackground(new java.awt.Color(204, 255, 51));
        btn_empleados.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EMPLEADO.png"))); // NOI18N
        btn_empleados.setText("Empleados");
        btn_empleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_empleados.setPreferredSize(new java.awt.Dimension(317, 109));
        btn_empleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empleadosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 230, 160));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 570, 180, 70));

        btn_reserva.setBackground(new java.awt.Color(204, 255, 51));
        btn_reserva.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btn_reserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RESERVA.png"))); // NOI18N
        btn_reserva.setText("Reserva");
        btn_reserva.setActionCommand("");
        btn_reserva.setAlignmentX(1.0F);
        btn_reserva.setBorder(new javax.swing.border.MatteBorder(null));
        btn_reserva.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_reserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_reserva.setIconTextGap(10);
        btn_reserva.setInheritsPopupMenu(true);
        btn_reserva.setMinimumSize(new java.awt.Dimension(317, 109));
        btn_reserva.setVerifyInputWhenFocusTarget(false);
        btn_reserva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_reserva.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_reservaMouseMoved(evt);
            }
        });
        btn_reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 230, 160));

        btn_huesped.setBackground(new java.awt.Color(204, 255, 51));
        btn_huesped.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn_huesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HUESPED.png"))); // NOI18N
        btn_huesped.setText("Huesped");
        btn_huesped.setAutoscrolls(true);
        btn_huesped.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_huesped.setVerifyInputWhenFocusTarget(false);
        btn_huesped.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_huesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huespedActionPerformed(evt);
            }
        });
        jPanel1.add(btn_huesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 230, 160));

        btn_facturas.setBackground(new java.awt.Color(204, 255, 51));
        btn_facturas.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn_facturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FACTURA.png"))); // NOI18N
        btn_facturas.setText("Control Facturas");
        btn_facturas.setAutoscrolls(true);
        btn_facturas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_facturas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_facturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facturasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_facturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 230, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO INVERSONES CAFIA.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 180, 240));

        btn_accesos.setBackground(new java.awt.Color(204, 255, 51));
        btn_accesos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btn_accesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ACCESOS.png"))); // NOI18N
        btn_accesos.setText("ACCESOS");
        btn_accesos.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn_accesos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_accesos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_accesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accesosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_accesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 230, 160));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("RESORT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 240, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDO.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 970, 670));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_habitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_habitacionesActionPerformed
        // TODO add your handling code here:
        new rooms().setVisible(true);
        this.dispose();
              
    }//GEN-LAST:event_btn_habitacionesActionPerformed

    private void btn_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_empleadosActionPerformed

    private void btn_accesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_accesosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservaActionPerformed
        // TODO add your handling code here:
        new reserva().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_reservaActionPerformed

    private void btn_huespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huespedActionPerformed
        // TODO add your handling code here:
        new huesped().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_huespedActionPerformed

    private void btn_facturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facturasActionPerformed
     
        new facturacion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_facturasActionPerformed

    private void btn_reservaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reservaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reservaMouseMoved

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accesos;
    private javax.swing.JButton btn_empleados;
    private javax.swing.JButton btn_facturas;
    private javax.swing.JButton btn_habitaciones;
    private javax.swing.JButton btn_huesped;
    private javax.swing.JButton btn_reserva;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
